name: CI toolkit

on: 
  push: 
    branches: [ master ]

jobs: 
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./devops-toolkit
    steps:
    - name: pull code
      uses: action/checkout@v4

    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: run check toolkit
      run: python main.py

