name: CI toolkit

on: 
  push: 
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: pull code
      uses: actions/checkout@v4

    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: SP login
      run: |
        az login --service-principal \
          --username ${{ secrets.ARM_CLIENT_ID }} \
          --password ${{ secrets.ARM_CLIENT_SECRET }} \
          --tenant ${{ secrets.ARM_TENANT_ID }}
        az account show --query "{subscription:id, name:name}" -o tsv

